### ISSUE TITLE
Create new checkbox field for checkout tracking: Get Involved

### ISSUE THREAD

**Issue by elichad** [carpentries/amy#2408]
Checkboxes with options for different contributions 
        Served as an Instructor or a helper at a Carpentries workshop
        Attended a Curriculum specific onboarding
        Attended an Instructor Meeting, regional meetup, or other community meeting
        Submitted a contribution to a Carpentries repository
        “Other” with free text entry

The checkbox should not allow multiple selections (pick one)

The option for submitting a contribution could enable a text field to add a URL to the specific contribution if available (stretch goal!)

Subtasks: 

- [ ] Create model to store different contributions
- [ ] Create 'Get Involved' field with options connected to the new model
- [ ] Create text field for extra content

Created automatically from an Asana task.

**Comment by elichad** [comment]
Extra comment from Maneesha:

We will have a new requirement called "Get Involved"
Recording this will include selecting one option from a series and filling in free-text or other field based on the option selected.  See list of options with corresponding fields.  

Be an Instructor or a helper at a Carpentries workshop (Date, Link to workshop website)
Attend a Curriculum specific onboarding (Date, Link to curriculum)
Attend an Instructor Meeting, regional meetup, or other Carpentries community meeting (Date, Description)
Make a contribution to a Carpentries GitHub repository (Date, Link to the contribution. Return error if this is not in a Carpentries repo.  Offer list of Carpentries repos.)
Other (free text)

In addition, we should have a general notes field for this step.
This will likely correspond to several AMY issues; putting things together here for now.
